Fix search
Search is broken due to a misplaced comment in `metadata.yaml`: what
was meant as a yaml comment was placed into SQL code and caused an
error.

```
INFO:     127.0.0.1:52279 - "GET /notebook/search?q=Python HTTP/1.1" 400 Bad Request
ERROR: conn=<sqlite3.Connection object at 0x1083bbf10>, sql = "select\n  notes_fts.rank,\n  notes.*,\n  snippet(notes_fts, -1, 'b4de2a49c8', '8c94a2ed4b', '...', 60) as snippet # https://www.sqlite.org/fts3.html#snippet\nfrom\n  notes\n  join notes_fts on notes.rowid = notes_fts.rowid\nwhere\n  notes_fts match case\n    :q\n    when '' then 'nomatchforthisterm'\n    else escape_fts(:q)\n  end\norder by\n  notes_fts.rank limit 40\n", params = {'q': 'Python'}: unrecognized token: "#"
```